import type { Batch } from '../../types/batch';

export const INITIAL_BATCHES: Batch[] = [
  { id: 'ba-btech', name: 'BA BTech', program: 'BA', track: 'BTech', poc: 'Srikar Kulkarni', traineeCount: 28, startMonth: 'March', avgScore: 89, completion: 94, attendanceRate: 96, submissionRate: 92, feedbackRating: 4.7, status: 'Active', members: ['John Doe', 'Priya Sharma', 'Bob Williams', 'Alice Smith', 'Vikram Singh'] },
  { id: 'ba-mba', name: 'BA MBA', program: 'BA', track: 'MBA', poc: 'Srikar Kulkarni', traineeCount: 22, startMonth: 'April', avgScore: 85, completion: 88, attendanceRate: 91, submissionRate: 85, feedbackRating: 4.3, status: 'Active', members: ['Sarah Connor', 'Rahul Verma', 'Neha Kapoor', 'Arjun Nair', 'Meera Iyer'] },
  { id: 'de-btech', name: 'Data Engineering BTech', program: 'Data Engineering', track: 'BTech', poc: 'Dinesh Paraman', traineeCount: 26, startMonth: 'March', avgScore: 87, completion: 91, attendanceRate: 94, submissionRate: 89, feedbackRating: 4.5, status: 'Active', members: ['Rahul Verma', 'Kunal Mehta', 'Sneha Rao', 'Aditya Joshi', 'Divya Menon'] },
  { id: 'de-mba', name: 'Data Engineering MBA', program: 'Data Engineering', track: 'MBA', poc: 'Dinesh Paraman', traineeCount: 20, startMonth: 'May', avgScore: 83, completion: 86, attendanceRate: 88, submissionRate: 80, feedbackRating: 4.1, status: 'Upcoming', members: ['Karan Malhotra', 'Pooja Reddy', 'Rohit Sinha', 'Isha Bansal', 'Varun Chawla'] },
  { id: 'aiml-btech', name: 'AI ML BTech', program: 'AI ML', track: 'BTech', poc: 'Junaid Mohammed', traineeCount: 24, startMonth: 'March', avgScore: 90, completion: 93, attendanceRate: 97, submissionRate: 94, feedbackRating: 4.8, status: 'Active', members: ['Ananya Patel', 'Sarah Connor', 'John Doe', 'Kavya Nambiar', 'Aman Gupta'] },
  { id: 'aiml-mba', name: 'AI ML MBA', program: 'AI ML', track: 'MBA', poc: 'Junaid Mohammed', traineeCount: 18, startMonth: 'June', avgScore: null, completion: null, attendanceRate: null, submissionRate: null, feedbackRating: null, status: 'Upcoming', members: ['Nikhil Rao', 'Tanya Sethi', 'Aditya Joshi', 'Priyanka Das', 'Rohan Kulkarni'] },
  { id: 'uiux-btech', name: 'UI/UX BTech', program: 'UI/UX', track: 'BTech', poc: 'Kaashyap Reddy', traineeCount: 25, startMonth: 'April', avgScore: 88, completion: 90, attendanceRate: 93, submissionRate: 87, feedbackRating: 4.4, status: 'Active', members: ['Vikram Singh', 'Alice Smith', 'Meera Iyer', 'Sneha Rao', 'Aditya Joshi'] },
  { id: 'uiux-mba', name: 'UI/UX MBA', program: 'UI/UX', track: 'MBA', poc: 'Kaashyap Reddy', traineeCount: 21, startMonth: 'May', avgScore: 84, completion: 87, attendanceRate: 90, submissionRate: 84, feedbackRating: 4.2, status: 'Active', members: ['Pooja Reddy', 'Karan Malhotra', 'Nikhil Rao', 'Isha Bansal', 'Divya Menon'] }
];
